# Generated by Django 3.2.8 on 2024-01-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0057_alter_employee_psswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('receives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to='user.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envia', to='user.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attached_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_emails')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emails')),
            ],
        ),
    ]
