# Generated by Django 3.2.8 on 2024-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='date_register',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emails',
            name='time_register',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
