# Generated by Django 3.2.8 on 2024-01-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20240102_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
