# Generated by Django 3.2.8 on 2024-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_remove_emails_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='is_read_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
