from django.contrib import admin
from .models import *

admin.site.register(Invoice)
admin.site.register(Details_Invoice)
admin.site.register(Payment_Forms)
admin.site.register(PaymentToPayInvoice)
admin.site.register(History_Invoice)
admin.site.register(History_Pass)
admin.site.register(Note_Credit_Product)

admin.site.register(Details_Remission)
admin.site.register(Payment_Forms_Remission)
admin.site.register(PassRemission)
admin.site.register(Remission)
admin.site.register(Details_Cotization)
admin.site.register(Payment_Forms_Cotization)
admin.site.register(PassCotization)
admin.site.register(Cotization)
admin.site.register(Details_Service)
admin.site.register(Payment_Forms_Service)
admin.site.register(PassService)
admin.site.register(Service)
admin.site.register(Details_OrderBuy)
admin.site.register(Payment_Forms_OrderBuy)
admin.site.register(OrderBuy)
admin.site.register(Details_InvoiceProvider)
admin.site.register(Payment_Forms_InvoiceProvider)
admin.site.register(InvoiceProvider)
admin.site.register(PaymentInvoiceProvider)
admin.site.register(InvoiceFrequent)
admin.site.register(InvoiceFromTicket)
admin.site.register(TicketGeneral)
admin.site.register(PaymentInvoice)
admin.site.register(NcToInvoice)
admin.site.register(CreditNote)
