# Generated by Django 3.2.8 on 2023-10-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0020_alter_branch_psswd'),
        ('setting', '0005_operation_type_document_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.municipalities')),
                ('type_document_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.type_document_i')),
                ('type_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.type_organization')),
                ('type_regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.type_regimen')),
            ],
        ),
    ]
