# Generated by Django 3.2 on 2024-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_wallet_customer_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.TextField(),
        ),
    ]
