# Generated by Django 3.2 on 2024-03-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_cfdi'),
        ('customer', '0007_alter_customer_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='List_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_deadline', models.CharField(max_length=50)),
                ('cfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cfdi', to='setting.cfdi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cfdi', to='customer.customer')),
                ('list_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_list_price', to='customer.list_price')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_form', to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_method', to='setting.payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='Associate_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
