# Generated by Django 3.2 on 2024-03-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_auto_20240312_2321'),
        ('customer', '0009_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type_document_i',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.type_document_i'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.type_organization'),
        ),
    ]
