# Generated by Django 3.2 on 2024-03-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20240314_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate_person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
