# Generated by Django 3.2 on 2024-05-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0036_auto_20240501_1441'),
        ('customer', '0011_alter_associate_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_information',
            name='list_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_list_price', to='setting.list_price'),
        ),
        migrations.DeleteModel(
            name='List_Price',
        ),
    ]
