# Generated by Django 3.2.8 on 2024-02-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_shopping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping',
            new_name='Report_Shopping',
        ),
    ]
