# Generated by Django 3.2.8 on 2024-01-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20240115_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bale_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
