# Generated by Django 3.2.8 on 2024-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_history_product_modified_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_product',
            name='timestamp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
