# Generated by Django 3.2 on 2024-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.BooleanField(default=True),
        ),
    ]
