# Generated by Django 3.2 on 2024-03-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_cfdi'),
        ('inventory', '0012_product_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_deadline', models.CharField(max_length=50)),
                ('cfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_cfdi', to='setting.cfdi')),
                ('list_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_list_price', to='inventory.list_price')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payment_form', to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payment_method', to='setting.payment_method')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Associate_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(max_length=15)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
