# Generated by Django 3.2 on 2024-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_associate_person_commercial_information_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='documentI',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
