# Generated by Django 3.2 on 2024-03-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_supplier_documenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate_person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
