# Generated by Django 3.2 on 2024-03-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_alter_tax_name'),
        ('inventory', '0015_alter_associate_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.unitmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.tax'),
        ),
    ]
