# Generated by Django 3.2 on 2024-05-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0037_auto_20240501_1508'),
        ('inventory', '0019_auto_20240501_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial_information',
            name='seller_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_seller', to='setting.sellerinfo'),
        ),
        migrations.AddField(
            model_name='commercial_information',
            name='term_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_term_payment', to='setting.termpayment'),
        ),
        migrations.AlterField(
            model_name='commercial_information',
            name='list_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_list_price', to='setting.list_price'),
        ),
    ]
