# Generated by Django 3.2 on 2024-05-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0172_alter_branch_psswd'),
        ('inventory', '0020_auto_20240501_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
