# Generated by Django 3.2 on 2024-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20240501_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_init',
            field=models.FloatField(default=0),
        ),
    ]
