# Generated by Django 3.2 on 2024-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_price_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.TextField(choices=[('Producto o Servicio', 'Producto o Servicio'), ('Gasto', 'Gasto'), ('Activo', 'Activo')], default='Producto o Servicio'),
        ),
    ]
