# Generated by Django 3.2 on 2024-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_in',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
