# Generated by Django 3.2 on 2024-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_product_code_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_in',
            field=models.CharField(max_length=50),
        ),
    ]
