# Generated by Django 3.2 on 2024-06-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0222_alter_branch_psswd'),
        ('setting', '0049_auto_20240605_1852'),
        ('inventory', '0026_alter_product_code_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_init', models.FloatField(default=0)),
                ('cant_min', models.FloatField(default=0)),
                ('cant_max', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.store')),
            ],
        ),
        migrations.CreateModel(
            name='PriceByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('list_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.list_price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
