# Generated by Django 3.2 on 2024-06-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_pricebyproduct_productinstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
