# Generated by Django 3.2 on 2024-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20240606_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='negative_sale',
            field=models.BooleanField(default=True),
        ),
    ]
