# Generated by Django 3.2 on 2024-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
