# Generated by Django 3.2.8 on 2023-10-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pass',
        ),
    ]
