# Generated by Django 3.2.8 on 2023-12-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0046_alter_branch_psswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ipo', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('branch_receives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_receives', to='company.branch')),
                ('branch_sends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_sends', to='company.branch')),
            ],
        ),
    ]
