# Generated by Django 3.2.8 on 2024-01-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20231226_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Entrance', 'Entrance'), ('Exit', 'Exit')], max_length=10)),
                ('branch', models.JSONField()),
                ('employee', models.JSONField()),
                ('transfer', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Transfer_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.transfer')),
            ],
        ),
    ]
