# Generated by Django 3.2.8 on 2024-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_alter_history_transfer_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
