# Generated by Django 3.2.8 on 2024-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='data_payroll',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
