# Generated by Django 3.2.8 on 2024-02-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20240221_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='was_sent',
            field=models.BooleanField(default=False),
        ),
    ]
