# Generated by Django 3.2.8 on 2023-10-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20231010_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='toke',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Oiq7FMx2pz', max_length=10),
        ),
    ]
