# Generated by Django 3.2.8 on 2023-10-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20231010_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='generated_to_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='XwI4eX02AC', max_length=10),
        ),
    ]
