# Generated by Django 3.2.8 on 2023-10-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20231011_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='cqGkPRGEgI', max_length=10),
        ),
        migrations.CreateModel(
            name='Consecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=1)),
                ('elec', models.IntegerField(default=1)),
                ('nc', models.IntegerField(default=1)),
                ('nd', models.IntegerField(default=1)),
                ('ne', models.IntegerField(default=1)),
                ('ds', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', unique=True)),
            ],
        ),
    ]
