# Generated by Django 3.2.8 on 2023-10-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20231011_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='8oEJ6LhBiN', max_length=10),
        ),
        migrations.AlterField(
            model_name='consecutive',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
