# Generated by Django 3.2.8 on 2023-10-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20231011_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='L0Nwopqc7C', max_length=10),
        ),
    ]
