# Generated by Django 3.2.8 on 2023-10-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Logo_Company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Kd1lHpRwDo', max_length=10),
        ),
    ]
