# Generated by Django 3.2.8 on 2023-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20231017_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='mmf5MxfiC8', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='Logo_Company/withOut.png', null=True, upload_to='Logo_Company'),
        ),
    ]
