# Generated by Django 3.2.8 on 2023-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20231017_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='5ekdT32ERy', max_length=10),
        ),
    ]
