# Generated by Django 3.2.8 on 2023-10-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='R2h1gYIN2B', max_length=10),
        ),
    ]
