# Generated by Django 3.2.8 on 2023-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutive',
            name='hd',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='guA9D9Aaqq', max_length=10),
        ),
    ]
