# Generated by Django 3.2.8 on 2023-10-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_auto_20231025_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('document', models.IntegerField()),
                ('user', models.IntegerField()),
                ('branch', models.IntegerField(unique=True)),
                ('date_registration', models.DateField(auto_now_add=True)),
                ('expiration_date', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='c0H6IXNPgf', max_length=10),
        ),
    ]
