# Generated by Django 3.2.8 on 2023-10-26 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20231025_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='mqpRSCHaEV', max_length=10),
        ),
        migrations.AlterField(
            model_name='license',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
