# Generated by Django 3.2.8 on 2023-10-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_auto_20231025_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='bISPBXCqyw', max_length=10),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_registration',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
