# Generated by Django 3.2.8 on 2023-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='r9chBgdlin', max_length=10),
        ),
    ]
