# Generated by Django 3.2.8 on 2023-10-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='robhmOfh6W', max_length=10),
        ),
    ]
