# Generated by Django 3.2.8 on 2023-10-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='R792ZhAFbW', max_length=10),
        ),
    ]
