# Generated by Django 3.2.8 on 2023-12-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='u7nfbviZU5', max_length=10),
        ),
    ]
