# Generated by Django 3.2.8 on 2023-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_auto_20231226_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='QlS602otEk', max_length=10),
        ),
    ]
