# Generated by Django 3.2.8 on 2023-12-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='xf5QwEcWuz', max_length=10),
        ),
    ]
