# Generated by Django 3.2.8 on 2023-12-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0050_auto_20231226_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='t6aOl5a0AY', max_length=10),
        ),
    ]
