# Generated by Django 3.2.8 on 2023-12-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0056_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='SmUGvQMmak', max_length=10),
        ),
    ]
