# Generated by Django 3.2.8 on 2023-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_auto_20231229_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='amount_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='z9xSTpvE67', max_length=10),
        ),
    ]
