# Generated by Django 3.2.8 on 2024-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_auto_20231229_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='drOpgNDNsf', max_length=10),
        ),
    ]
