# Generated by Django 3.2.8 on 2024-01-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='HlKdlb5cLy', max_length=10),
        ),
    ]
