# Generated by Django 3.2.8 on 2024-01-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='TQ61CvZtuZ', max_length=10),
        ),
    ]
