# Generated by Django 3.2.8 on 2024-01-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='csnkZWSwPZ', max_length=10),
        ),
    ]
