# Generated by Django 3.2.8 on 2024-01-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='sQqC7u3Qrd', max_length=10),
        ),
    ]
