# Generated by Django 3.2.8 on 2024-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='7S9dyUSUu5', max_length=10),
        ),
    ]
