# Generated by Django 3.2.8 on 2024-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0084_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='wXZVHX7nqv', max_length=10),
        ),
    ]
