# Generated by Django 3.2.8 on 2024-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0085_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='testsetid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='pJo8hRxPDs', max_length=10),
        ),
    ]
