# Generated by Django 3.2.8 on 2024-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0086_auto_20240213_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='40n6MJ5DUk', max_length=10),
        ),
    ]
