# Generated by Django 3.2.8 on 2024-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0087_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='fMNIML0YN9', max_length=10),
        ),
    ]
