# Generated by Django 3.2.8 on 2024-02-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0091_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutive',
            name='nc_by_product',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='sU9n8Tegx9', max_length=10),
        ),
    ]
