# Generated by Django 3.2.8 on 2024-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0092_auto_20240220_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='aXeS6Q27I4', max_length=10),
        ),
    ]
