# Generated by Django 3.2.8 on 2024-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0093_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='cv5fLAZrue', max_length=10),
        ),
    ]
