# Generated by Django 3.2.8 on 2024-02-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_remove_operation_value_coin'),
        ('company', '0095_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.municipalities'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ABZ6msAYOh', max_length=10),
        ),
    ]
