# Generated by Django 3.2.8 on 2024-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0099_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='4Ag5xfDRIi', max_length=10),
        ),
    ]
