# Generated by Django 3.2.8 on 2024-02-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0105_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='9JGzPEy08d', max_length=10),
        ),
    ]
