# Generated by Django 3.2.8 on 2024-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0108_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='rA2gi8Y9X7', max_length=10),
        ),
    ]
