# Generated by Django 3.2 on 2024-03-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0111_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='eYyvCqMjvx', max_length=10),
        ),
    ]
