# Generated by Django 3.2 on 2024-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0113_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='96K4MXEnEI', max_length=10),
        ),
    ]
