# Generated by Django 3.2 on 2024-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0115_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='MiI12TZDZC', max_length=10),
        ),
    ]
