# Generated by Django 3.2 on 2024-03-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0117_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='y8z9UUYZhk', max_length=10),
        ),
    ]
