# Generated by Django 3.2 on 2024-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0121_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='4Jk6zqLP4p', max_length=10),
        ),
    ]
