# Generated by Django 3.2 on 2024-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0122_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='pNBqtbGLEH', max_length=10),
        ),
    ]
