# Generated by Django 3.2 on 2024-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0125_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='PuEkyGJOVx', max_length=10),
        ),
    ]
