# Generated by Django 3.2 on 2024-03-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0126_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='d5V4z9h3qo', max_length=10),
        ),
    ]
