# Generated by Django 3.2 on 2024-03-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0127_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='QPMXZ8WDDA', max_length=10),
        ),
    ]
