# Generated by Django 3.2 on 2024-03-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0129_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='kfx7bI1XoK', max_length=10),
        ),
    ]
