# Generated by Django 3.2 on 2024-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0130_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='viwFEwOPt0', max_length=10),
        ),
    ]
