# Generated by Django 3.2 on 2024-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0131_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='TwSbRS3JWe', max_length=10),
        ),
    ]
