# Generated by Django 3.2 on 2024-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0135_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='jznsgOwqUR', max_length=10),
        ),
    ]
