# Generated by Django 3.2 on 2024-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0136_auto_20240411_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ba4LAC7OiF', max_length=10),
        ),
    ]
