# Generated by Django 3.2 on 2024-04-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_sector'),
        ('company', '0137_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.sector'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='tcVgIH932L', max_length=10),
        ),
    ]
