# Generated by Django 3.2 on 2024-04-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0139_auto_20240411_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='IfvRia0OI0', max_length=10),
        ),
    ]
