# Generated by Django 3.2 on 2024-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0140_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='COP4cWVhI9', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='documentI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
