# Generated by Django 3.2 on 2024-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0141_auto_20240411_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Q9JrrmTu9G', max_length=10),
        ),
    ]
