# Generated by Django 3.2 on 2024-04-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0142_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='n1XGiPI4nr', max_length=10),
        ),
    ]
