# Generated by Django 3.2 on 2024-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0145_auto_20240419_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Lw93nZp1Qb', max_length=10),
        ),
    ]
