# Generated by Django 3.2 on 2024-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0149_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='C0zANvg4yM', max_length=10),
        ),
    ]
