# Generated by Django 3.2 on 2024-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0150_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='pLrXnwH0zS', max_length=10),
        ),
    ]
