# Generated by Django 3.2 on 2024-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0159_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='TjyPWUFKGC', max_length=10),
        ),
    ]
