# Generated by Django 3.2 on 2024-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0160_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='yDICE9H11r', max_length=10),
        ),
    ]
