# Generated by Django 3.2 on 2024-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0163_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='VX5MehZUek', max_length=10),
        ),
    ]
