# Generated by Django 3.2 on 2024-04-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0164_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='5JwSFMSuz2', max_length=10),
        ),
    ]
