# Generated by Django 3.2 on 2024-04-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0165_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='4Wnv2b73Ui', max_length=10),
        ),
    ]
