# Generated by Django 3.2 on 2024-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0168_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='QTxUc74E5K', max_length=10),
        ),
    ]
