# Generated by Django 3.2 on 2024-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0173_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='XsIgctOiFZ', max_length=10),
        ),
    ]
