# Generated by Django 3.2 on 2024-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0174_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='ytQJS9z3Rz', max_length=10),
        ),
    ]
