# Generated by Django 3.2 on 2024-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0175_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Ld8EISVvp1', max_length=10),
        ),
    ]
