# Generated by Django 3.2 on 2024-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0176_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='xWEQy89kn3', max_length=10),
        ),
    ]
