# Generated by Django 3.2 on 2024-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0177_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='973IlPO7z8', max_length=10),
        ),
    ]
