# Generated by Django 3.2 on 2024-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0181_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='LGivhbf83v', max_length=10),
        ),
    ]
