# Generated by Django 3.2 on 2024-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0183_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='auFiFXmy75', max_length=10),
        ),
    ]
