# Generated by Django 3.2 on 2024-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0185_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='4v7IV8pqke', max_length=10),
        ),
    ]
