# Generated by Django 3.2 on 2024-05-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0186_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Me8bkwv91J', max_length=10),
        ),
        migrations.CreateModel(
            name='SerieFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(blank=True, choices=[('Factura de venta', 'Factura de venta'), ('Ticket de venta', 'Ticket de venta'), ('Ajuste de inventario', 'Ajuste de inventario'), ('Factura de traslado', 'Factura de traslado')], max_length=30, null=True)),
                ('name', models.CharField(max_length=100)),
                ('serie_folio_auto', models.BooleanField(default=True)),
                ('serie', models.CharField(max_length=30)),
                ('folio_from', models.IntegerField()),
                ('folio_to', models.IntegerField()),
                ('preferida', models.BooleanField(default=True)),
                ('pie_invoice', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
            ],
        ),
    ]
