# Generated by Django 3.2 on 2024-05-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0188_auto_20240509_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='QVfvk97WGi', max_length=10),
        ),
        migrations.AlterField(
            model_name='seriefolio',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
