# Generated by Django 3.2 on 2024-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0189_auto_20240509_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='E756Bug2Ec', max_length=10),
        ),
    ]
