# Generated by Django 3.2 on 2024-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0192_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='8IE1XP9PCA', max_length=10),
        ),
    ]
