# Generated by Django 3.2 on 2024-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0195_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='4A9eER93AO', max_length=10),
        ),
    ]
