# Generated by Django 3.2 on 2024-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0197_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='NqliXnmjrC', max_length=10),
        ),
    ]
