# Generated by Django 3.2 on 2024-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0198_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='IZj0XXf7yD', max_length=10),
        ),
    ]
