# Generated by Django 3.2 on 2024-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0202_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='PPNY7bfScp', max_length=10),
        ),
    ]
