# Generated by Django 3.2 on 2024-05-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0205_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='0i3gmNMOW4', max_length=10),
        ),
    ]
