# Generated by Django 3.2 on 2024-05-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0206_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='7LqtRcoTex', max_length=10),
        ),
    ]
