# Generated by Django 3.2 on 2024-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0207_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='rNyDb8dzgb', max_length=10),
        ),
    ]
