# Generated by Django 3.2 on 2024-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0208_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='0c3umTr60j', max_length=10),
        ),
    ]
