# Generated by Django 3.2 on 2024-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0211_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Ldh1eFkK14', max_length=10),
        ),
    ]
