# Generated by Django 3.2 on 2024-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0219_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='T5UYmoh40I', max_length=10),
        ),
    ]
