# Generated by Django 3.2 on 2024-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0222_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='BlV0wBcXZR', max_length=10),
        ),
    ]
