# Generated by Django 3.2 on 2024-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0223_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='tj79aAqNc9', max_length=10),
        ),
    ]
