# Generated by Django 3.2 on 2024-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0225_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='GbcYnSlcpZ', max_length=10),
        ),
    ]
