# Generated by Django 3.2 on 2024-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0226_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cer_file',
            field=models.FileField(blank=True, null=True, upload_to='cert'),
        ),
        migrations.AddField(
            model_name='company',
            name='key_file',
            field=models.FileField(blank=True, null=True, upload_to='cert'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='8tMwyZgirZ', max_length=10),
        ),
    ]
