# Generated by Django 3.2 on 2024-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0227_auto_20240611_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pwd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='u5nHIbXNUk', max_length=10),
        ),
    ]
