# Generated by Django 3.2 on 2024-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0228_auto_20240611_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='FTfi4Wi9Xr', max_length=10),
        ),
    ]
