# Generated by Django 3.2 on 2024-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0229_auto_20240611_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='SpVVuYUqjH', max_length=10),
        ),
    ]
