# Generated by Django 3.2 on 2024-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0230_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='8cUJo8t0Tw', max_length=10),
        ),
    ]
