# Generated by Django 3.2 on 2024-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0231_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='OQtjExdUh6', max_length=10),
        ),
    ]
