# Generated by Django 3.2 on 2024-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0233_alter_branch_psswd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consecutive',
            old_name='ds',
            new_name='ct',
        ),
        migrations.RenameField(
            model_name='consecutive',
            old_name='hd',
            new_name='oc',
        ),
        migrations.RenameField(
            model_name='consecutive',
            old_name='nc_by_product',
            new_name='rm',
        ),
        migrations.AddField(
            model_name='consecutive',
            name='se',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='5SLZRbCewc', max_length=10),
        ),
    ]
