# Generated by Django 3.2 on 2024-06-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0234_auto_20240612_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='LiPUQ4W2dt', max_length=10),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_account', models.CharField(choices=[('Banco nacional', 'Banco nacional'), ('Tarjeta de credito', 'Tarjeta de credito'), ('Efectivo', 'Efectivo'), ('Banco extranjero', 'Banco extranjero')], default='Banco nacional', max_length=30)),
                ('name', models.CharField(max_length=512)),
                ('account_number', models.CharField(max_length=512)),
                ('amount_init', models.FloatField()),
                ('date_amount_init', models.DateField()),
                ('description', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
            ],
        ),
    ]
