# Generated by Django 3.2 on 2024-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0235_auto_20240625_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='NV5YWMmvBK', max_length=10),
        ),
    ]
