# Generated by Django 3.2 on 2024-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0236_auto_20240625_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='state',
            field=models.CharField(choices=[('No conectado', 'No conectado')], default='No conectado', max_length=30),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='PlWKOniCna', max_length=10),
        ),
    ]
