# Generated by Django 3.2 on 2024-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0237_auto_20240625_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='6902IpXFIZ', max_length=10),
        ),
    ]
