# Generated by Django 3.2 on 2024-06-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0238_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='VQXSJ4dJ0P', max_length=10),
        ),
    ]
