# Generated by Django 3.2 on 2024-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0240_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutive',
            name='ni',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='qRRFesEQ16', max_length=10),
        ),
    ]
