# Generated by Django 3.2 on 2024-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0241_auto_20240701_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='wDl7jPi0XI', max_length=10),
        ),
    ]
