# Generated by Django 3.2 on 2024-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0244_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='bwxxcWAlDs', max_length=10),
        ),
    ]
