# Generated by Django 3.2 on 2024-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0247_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='21MpEcaztn', max_length=10),
        ),
    ]
