# Generated by Django 3.2 on 2024-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0250_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='vskIeCIUxR', max_length=10),
        ),
    ]
