# Generated by Django 3.2 on 2024-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0251_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='G5uSqNaqnt', max_length=10),
        ),
    ]
