# Generated by Django 3.2 on 2024-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0253_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='wM6YVt90Gn', max_length=10),
        ),
    ]
