# Generated by Django 3.2 on 2024-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0254_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='y0nTvLj09M', max_length=10),
        ),
    ]
