# Generated by Django 3.2 on 2024-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0256_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='EvSZh8LAug', max_length=10),
        ),
    ]
