# Generated by Django 3.2 on 2024-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0258_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='8hAyYk8unS', max_length=10),
        ),
    ]
