# Generated by Django 3.2 on 2024-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0261_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_commercial',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='k0IBbsNt6V', max_length=10),
        ),
    ]
