# Generated by Django 3.2 on 2024-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0262_auto_20240726_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='tLAxgRDQMM', max_length=10),
        ),
    ]
