# Generated by Django 3.2 on 2024-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0263_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='gK6p7Di5PN', max_length=10),
        ),
    ]
