# Generated by Django 3.2 on 2024-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0266_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='uJ2oSHLYeQ', max_length=10),
        ),
    ]
