# Generated by Django 3.2 on 2024-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0267_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='S46CJJDWWQ', max_length=10),
        ),
    ]
