# Generated by Django 3.2 on 2024-08-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0268_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='isPMAN4Q4U', max_length=10),
        ),
    ]
