# Generated by Django 3.2 on 2024-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0270_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='2Lg8Oszz8g', max_length=10),
        ),
    ]
