# Generated by Django 3.2 on 2024-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0271_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='CcFWNBTG1z', max_length=10),
        ),
    ]
