# Generated by Django 3.2 on 2024-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0273_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='8fIZ03AeY5', max_length=10),
        ),
    ]
