# Generated by Django 3.2.8 on 2023-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_payroll_type_document_identification_sub_type_worker_type_contract_type_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_type_document_identification',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_type_worker',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type_contract',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type_document',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type_organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type_regimen',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type_worker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
