# Generated by Django 3.2.8 on 2023-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_operation_type_document_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
