# Generated by Django 3.2.8 on 2023-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='value_coin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
