# Generated by Django 3.2 on 2024-03-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_unitmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('tax_num', models.IntegerField(default=0)),
            ],
        ),
    ]
