# Generated by Django 3.2 on 2024-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
