# Generated by Django 3.2 on 2024-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_alter_tax_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
