# Generated by Django 3.2 on 2024-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('days', models.IntegerField(default=0)),
            ],
        ),
    ]
