# Generated by Django 3.2 on 2024-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_termpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='termpayment',
            name='branch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
