# Generated by Django 3.2 on 2024-04-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_termpayment_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermAndCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notas', models.TextField()),
                ('branch', models.IntegerField()),
            ],
        ),
    ]
