# Generated by Django 3.2 on 2024-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_termandcond'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rfc', models.TextField(max_length=200)),
                ('observation', models.TextField()),
                ('branch', models.IntegerField()),
            ],
        ),
    ]
