# Generated by Django 3.2 on 2024-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0020_sellerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='acreditable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='type_tax',
            field=models.TextField(choices=[('IVA', 'IVA'), ('Otro', 'Otro'), ('Local', 'Local'), ('IEPS', 'IEPS'), ('IVA Exento', 'IVA Exento '), ('IEPS Exento', 'IEPS Exento')], default='IVA'),
        ),
    ]
