# Generated by Django 3.2 on 2024-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0021_auto_20240424_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='branch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax',
            name='type_tax',
            field=models.TextField(choices=[('IVA', 'IVA'), ('Otro', 'Otro'), ('Local', 'Local'), ('IEPS', 'IEPS'), ('IVA Exento', 'IVA Exento'), ('IEPS Exento', 'IEPS Exento')], default='IVA'),
        ),
    ]
