# Generated by Django 3.2 on 2024-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0023_auto_20240424_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='path',
            field=models.TextField(choices=[('IVA', 'IVA'), ('Otro', 'Otro'), ('Local', 'Local'), ('IEPS', 'IEPS'), ('IVA Exento', 'IVA Exento'), ('IEPS Exento', 'IEPS Exento'), ('Retencion de ISR', 'Retencion de ISR'), ('Retencion de IVA', 'Retencion de IVA'), ('Retencion de IVA por fletes', 'Retencion de IVA por fletes'), ('Otro tipo de retencion', 'Otro tipo de retencion'), ('Retencion local', 'Retencion local')], default='tax', max_length=30),
        ),
    ]
