# Generated by Django 3.2 on 2024-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0024_alter_tax_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='path',
            field=models.TextField(choices=[('tax', 'tax'), ('retention', 'retention')], default='tax', max_length=30),
        ),
    ]
