# Generated by Django 3.2 on 2024-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0025_alter_tax_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('branch', models.IntegerField()),
            ],
        ),
    ]
