# Generated by Django 3.2 on 2024-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0026_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='asunto',
            field=models.CharField(max_length=150),
        ),
    ]
