# Generated by Django 3.2 on 2024-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0028_auto_20240424_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='option',
            field=models.TextField(choices=[('template', 'template'), ('notify', 'notify')], default='notify', max_length=30),
        ),
    ]
