# Generated by Django 3.2 on 2024-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0030_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdi',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cfdi',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
