# Generated by Django 3.2 on 2024-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0031_auto_20240426_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProdServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
