# Generated by Django 3.2 on 2024-04-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0032_claveprodserv'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='municipality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='setting.municipalities'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.postalcode')),
            ],
        ),
    ]
