# Generated by Django 3.2 on 2024-04-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0033_auto_20240426_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalities',
            name='_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
