# Generated by Django 3.2 on 2024-04-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0034_auto_20240426_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Update', 'Update'), ('Delete', 'Delete'), ('Annulled', 'Annulled')], max_length=10, null=True)),
                ('class_models', models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Inventory', 'Inventory'), ('Invoice', 'Invoice'), ('Remission', 'Remission'), ('Cotization', 'Cotization'), ('Service', 'Service'), ('Provider', 'Provider'), ('Spent', 'Spent'), ('Employee', 'Employee'), ('Store', 'Store'), ('Empresa', 'Empresa'), ('TermPayment', 'TermPayment'), ('TermAndCond', 'TermAndCond'), ('Resolution', 'Resolution'), ('Seller', 'Seller'), ('Tax', 'Tax'), ('Retention', 'Retention'), ('Template', 'Template'), ('Notification', 'Notification'), ('Accounting', 'Accounting'), ('Suscription', 'Suscription')], max_length=50, null=True)),
                ('class_models_json', models.JSONField()),
                ('employee', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('branch', models.IntegerField()),
            ],
        ),
    ]
