# Generated by Django 3.2 on 2024-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0035_historygeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
                ('principal', models.BooleanField(default=False)),
                ('type_price', models.TextField(choices=[('valor', 'valor'), ('porcentaje', 'porcentaje')], default='valor')),
                ('branch', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='historygeneral',
            name='class_models',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Inventory', 'Inventory'), ('Invoice', 'Invoice'), ('Remission', 'Remission'), ('Cotization', 'Cotization'), ('Service', 'Service'), ('Provider', 'Provider'), ('Spent', 'Spent'), ('Employee', 'Employee'), ('Store', 'Store'), ('Empresa', 'Empresa'), ('TermPayment', 'TermPayment'), ('TermAndCond', 'TermAndCond'), ('Resolution', 'Resolution'), ('Seller', 'Seller'), ('Tax', 'Tax'), ('Retention', 'Retention'), ('Template', 'Template'), ('Notification', 'Notification'), ('Accounting', 'Accounting'), ('Suscription', 'Suscription'), ('Branch', 'Branch')], max_length=50, null=True),
        ),
    ]
