# Generated by Django 3.2 on 2024-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0036_auto_20240501_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_price',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historygeneral',
            name='class_models',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Inventory', 'Inventory'), ('Invoice', 'Invoice'), ('Remission', 'Remission'), ('Cotization', 'Cotization'), ('Service', 'Service'), ('Provider', 'Provider'), ('Spent', 'Spent'), ('Employee', 'Employee'), ('Store', 'Store'), ('Empresa', 'Empresa'), ('TermPayment', 'TermPayment'), ('TermAndCond', 'TermAndCond'), ('Resolution', 'Resolution'), ('Seller', 'Seller'), ('Tax', 'Tax'), ('Retention', 'Retention'), ('Template', 'Template'), ('Notification', 'Notification'), ('Accounting', 'Accounting'), ('Suscription', 'Suscription'), ('Branch', 'Branch'), ('List_price', 'List_price')], max_length=50, null=True),
        ),
    ]
