# Generated by Django 3.2 on 2024-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0038_alter_historygeneral_class_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_num',
            field=models.FloatField(default=0),
        ),
    ]
