# Generated by Django 3.2 on 2024-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0039_alter_tax_tax_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_regimen',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
