# Generated by Django 3.2 on 2024-05-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0040_type_regimen_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
