# Generated by Django 3.2 on 2024-05-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0041_payment_method_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_form',
            name='_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
