# Generated by Django 3.2 on 2024-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0042_alter_payment_form__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
