# Generated by Django 3.2 on 2024-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0043_motivocancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveprodserv',
            name='complementoQueDebeIncluir',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='estimuloFranjaFronteriza',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='fechaFinVigencia',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='fechaInicioVigencia',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='incluirIEPSTrasladado',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='incluirIVATrasladado',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='palabrasSimilares',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
