# Generated by Django 3.2 on 2024-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0046_alter_historygeneral_class_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygeneral',
            name='class_models',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Inventory', 'Inventory'), ('Invoice', 'Invoice'), ('Remission', 'Remission'), ('Cotization', 'Cotization'), ('Service', 'Service'), ('Provider', 'Provider'), ('Spent', 'Spent'), ('Employee', 'Employee'), ('Store', 'Store'), ('Empresa', 'Empresa'), ('TermPayment', 'TermPayment'), ('TermAndCond', 'TermAndCond'), ('Resolution', 'Resolution'), ('Seller', 'Seller'), ('Tax', 'Tax'), ('Retention', 'Retention'), ('Template', 'Template'), ('Notification', 'Notification'), ('Accounting', 'Accounting'), ('Suscription', 'Suscription'), ('Branch', 'Branch'), ('List_price', 'List_price'), ('Category', 'Category'), ('Order_buy', 'Order_buy'), ('Invoice_provider', 'Invoice_provider'), ('Bil_to_pay', 'Bil_to_pay')], max_length=50, null=True),
        ),
    ]
