# Generated by Django 3.2 on 2024-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0049_auto_20240605_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('type_message', models.TextField(choices=[('CheckEmail', 'CheckEmail')], default='CheckEmail')),
            ],
        ),
    ]
