# Generated by Django 3.2 on 2024-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0050_emailsmtp_messageemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageemail',
            name='type_message',
            field=models.TextField(choices=[('CheckEmail', 'CheckEmail'), ('SendFile', 'SendFile')], default='CheckEmail'),
        ),
    ]
