# Generated by Django 3.2 on 2024-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0052_alter_historygeneral_class_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='termandcond',
            name='pie_invoice',
            field=models.TextField(default=''),
        ),
    ]
