# Generated by Django 3.2 on 2024-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0053_termandcond_pie_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='termandcond',
            name='state_account',
            field=models.BooleanField(default=False),
        ),
    ]
