# Generated by Django 3.2.8 on 2023-10-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0002_payroll_type_document_identification_sub_type_worker_type_contract_type_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_risk_pension', models.BooleanField()),
                ('identification_number', models.IntegerField()),
                ('surname', models.CharField(max_length=255)),
                ('second_surname', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('integral_salary', models.BooleanField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('municipality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.municipalities')),
                ('payroll_type_document_identification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payroll_type_document_identification')),
                ('sub_type_worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.sub_type_worker')),
                ('type_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.type_contract')),
                ('type_worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.type_worker')),
            ],
        ),
    ]
