# Generated by Django 3.2.8 on 2023-10-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_branch_psswd'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Modified', 'Modified'), ('Deleted', 'Deleted')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='hFYAztDwYjT7DxWMcWDV', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
