# Generated by Django 3.2.8 on 2023-10-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231004_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_employee',
            name='recorded_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history_employee',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='history_employee',
            name='user_who_registers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='feg2lzxYWb9FrkUQ946X', max_length=20),
        ),
        migrations.AlterField(
            model_name='history_employee',
            name='action',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Modified', 'Modified'), ('Deleted', 'Deleted')], max_length=10, null=True),
        ),
    ]
