# Generated by Django 3.2.8 on 2023-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='nhCr2G9Ri61TiQak3aTX', max_length=20),
        ),
    ]
