# Generated by Django 3.2.8 on 2023-10-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='YE51y7TUd6yvdGDvBe4z', max_length=20),
        ),
    ]
