# Generated by Django 3.2.8 on 2023-10-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='XhLwNZg2z1Zcb5sPqXoZ', max_length=20),
        ),
    ]
