# Generated by Django 3.2.8 on 2023-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='HGPHrUe0D0EdbS71q1rd', max_length=20),
        ),
    ]
