# Generated by Django 3.2.8 on 2023-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='I6J5OwHQqOoURNDs3BGf', max_length=20),
        ),
    ]
