# Generated by Django 3.2.8 on 2023-10-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='57GGrOFLSyciArpqRSlV', max_length=20),
        ),
    ]
