# Generated by Django 3.2.8 on 2023-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='9UiGl0XnhXoGhO5kYjbL', max_length=20),
        ),
    ]
