# Generated by Django 3.2.8 on 2023-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20231017_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='7zBiKGnPkTHThjt6sF3o', max_length=20, unique=True),
        ),
    ]
