# Generated by Django 3.2.8 on 2023-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_permission'),
        ('user', '0027_alter_employee_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='setting.Permission'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='nf6HyuNBv7p2jSnUM40H', max_length=20, unique=True),
        ),
    ]
