# Generated by Django 3.2.8 on 2023-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='fl9ynUZCNKULryrWj6T7', max_length=20, unique=True),
        ),
    ]
