# Generated by Django 3.2.8 on 2023-10-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='kMAPKTRfQtSd16eHZ5mN', max_length=20, unique=True),
        ),
    ]
