# Generated by Django 3.2.8 on 2023-12-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_permission'),
        ('user', '0038_auto_20231030_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_risk_pension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='integral_salary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.municipalities'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payroll_type_document_identification_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.payroll_type_document_identification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='evP3cuDdiHizB6HzK2fp', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sub_type_worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.sub_type_worker'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_contract_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.type_contract'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.type_worker'),
        ),
    ]
