# Generated by Django 3.2.8 on 2023-12-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='cnV2P3BtLQ3Yb6p3bxU0', max_length=20, unique=True),
        ),
    ]
