# Generated by Django 3.2.8 on 2023-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='o6eg2eK8NSICr56jyaI5', max_length=20, unique=True),
        ),
    ]
