# Generated by Django 3.2.8 on 2023-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='nbADoO4DvQGYLVEoEgIz', max_length=20, unique=True),
        ),
    ]
