# Generated by Django 3.2.8 on 2023-12-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='5pLsKZvArPighyzLc2B2', max_length=20, unique=True),
        ),
    ]
