# Generated by Django 3.2.8 on 2023-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='F2REPibfiHroG5tjUSGz', max_length=20, unique=True),
        ),
    ]
