# Generated by Django 3.2.8 on 2023-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='epmuBES1dNi3OuU2h4Cd', max_length=20, unique=True),
        ),
    ]
