# Generated by Django 3.2.8 on 2024-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_auto_20240103_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='rXtW9vRFhEUqXhBGiOmU', max_length=20, unique=True),
        ),
    ]
