# Generated by Django 3.2.8 on 2024-01-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='3hJFxOIbcOUMggmWX8s9', max_length=20, unique=True),
        ),
    ]
