# Generated by Django 3.2.8 on 2024-01-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='eJEcPTiTXr1IkE3l5TTQ', max_length=20, unique=True),
        ),
    ]
