# Generated by Django 3.2.8 on 2024-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='DJox4xl1EAPE7c86HcdH', max_length=20, unique=True),
        ),
    ]
