# Generated by Django 3.2.8 on 2024-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='pFOGCke4kcBoxgsfdA4x', max_length=20, unique=True),
        ),
    ]
