# Generated by Django 3.2.8 on 2024-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='rmPUCNts2w2JFemJiBfa', max_length=20, unique=True),
        ),
    ]
