# Generated by Django 3.2.8 on 2024-02-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='koSvANrIAhX8eXm7akuH', max_length=20, unique=True),
        ),
    ]
