# Generated by Django 3.2.8 on 2024-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='I0JxGU3CFxxXdbpHzbnL', max_length=20, unique=True),
        ),
    ]
