# Generated by Django 3.2.8 on 2024-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0081_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='vKZbPO4GmwSlBy2MjMBV', max_length=20, unique=True),
        ),
    ]
