# Generated by Django 3.2.8 on 2024-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='992NSDy1UJ6rWZ8IgOIr', max_length=20, unique=True),
        ),
    ]
