# Generated by Django 3.2.8 on 2024-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='fmbxuaSMaf1Shaju9Cid', max_length=20, unique=True),
        ),
    ]
