# Generated by Django 3.2.8 on 2024-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0090_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='3WDMv63fON8zbHdTB6Wj', max_length=20, unique=True),
        ),
    ]
