# Generated by Django 3.2.8 on 2024-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0100_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='12gxRDa9GiONFLC5CfpX', max_length=20, unique=True),
        ),
    ]
