# Generated by Django 3.2.8 on 2024-02-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0101_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='yVMRvGG9Bx7OzxKYHVmh', max_length=20, unique=True),
        ),
    ]
