# Generated by Django 3.2.8 on 2024-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0103_auto_20240226_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='cgDNt99vLGPR9ygDlGKP', max_length=20, unique=True),
        ),
    ]
