# Generated by Django 3.2.8 on 2024-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0106_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='awLxWXKNYMa6RT9Rhw2V', max_length=20, unique=True),
        ),
    ]
