# Generated by Django 3.2 on 2024-03-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0107_alter_employee_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_django',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Jj1yqR01ePxR23WEn5JS', max_length=20, unique=True),
        ),
    ]
