# Generated by Django 3.2 on 2024-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0108_auto_20240308_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='KvXirIaNRNQf1NZdKIXV', max_length=20, unique=True),
        ),
    ]
