# Generated by Django 3.2 on 2024-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0109_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='QBCxuxzU9shLEVBqkEom', max_length=20, unique=True),
        ),
    ]
