# Generated by Django 3.2 on 2024-03-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0112_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='lIpdcEwJReKJTuo4dmCQ', max_length=20),
        ),
    ]
