# Generated by Django 3.2 on 2024-03-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0113_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='iva6c93qCx8De2mHhS8C', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
