# Generated by Django 3.2 on 2024-03-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0114_auto_20240312_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='c9wXAIiRINPFgIG0RYsK', max_length=20),
        ),
    ]
