# Generated by Django 3.2 on 2024-03-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0115_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='rhwolhDlTsgJg77rvcZK', max_length=20),
        ),
    ]
