# Generated by Django 3.2 on 2024-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0116_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='YpSzFb8krrgwBNOcHkqm', max_length=20),
        ),
    ]
