# Generated by Django 3.2 on 2024-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0117_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='GEk4wW0untBK55sWKilJ', max_length=20),
        ),
    ]
