# Generated by Django 3.2 on 2024-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0118_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='1PtIP2T0ju18eJ95UTim', max_length=20),
        ),
    ]
