# Generated by Django 3.2 on 2024-03-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0120_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='C9OcnyuTYbteTtrVKvoq', max_length=20),
        ),
    ]
