# Generated by Django 3.2 on 2024-03-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0122_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='5C6Ct1tS9KkzxFUTcrRV', max_length=20),
        ),
    ]
