# Generated by Django 3.2 on 2024-03-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0123_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='3KhO4pNg949NcAtE9Rnz', max_length=20),
        ),
    ]
