# Generated by Django 3.2 on 2024-03-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0125_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='tg5ggkVGx3JFu7P27WcL', max_length=20),
        ),
    ]
