# Generated by Django 3.2 on 2024-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0126_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='cFyTitFHTVXa4ziOO0kN', max_length=20),
        ),
    ]
