# Generated by Django 3.2 on 2024-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0127_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='AZQdBMIiI0J1i0u9HRy9', max_length=20),
        ),
    ]
