# Generated by Django 3.2 on 2024-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0129_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='lsONXCPnNpUhDyvF779i', max_length=20),
        ),
    ]
