# Generated by Django 3.2 on 2024-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0131_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Vlhg3jKfhkVSxfsx8Kfj', max_length=20),
        ),
    ]
