# Generated by Django 3.2 on 2024-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0132_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='L4sXLensrJ0S3V6u8laI', max_length=20),
        ),
    ]
