# Generated by Django 3.2 on 2024-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0134_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='lj3mrU7pCNRmajAQxa1n', max_length=20),
        ),
    ]
