# Generated by Django 3.2 on 2024-04-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0135_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='crAT0UQDOO6AgiwO6uNR', max_length=20),
        ),
    ]
