# Generated by Django 3.2 on 2024-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0136_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='bjKOIUBGg7fGPsJXbacw', max_length=20),
        ),
    ]
