# Generated by Django 3.2 on 2024-04-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0138_auto_20240411_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='internal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Fp4CVAxapzunzELgVfzX', max_length=20),
        ),
    ]
