# Generated by Django 3.2 on 2024-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0139_auto_20240412_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='wKe2kuiMZp4pnnZQpQwI', max_length=20),
        ),
    ]
