# Generated by Django 3.2 on 2024-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0140_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='2jDhIIj6pObanQkh0U4J', max_length=20),
        ),
    ]
