# Generated by Django 3.2 on 2024-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0141_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='QoobSjgDKZ2FSPvhFekF', max_length=20),
        ),
    ]
