# Generated by Django 3.2 on 2024-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0142_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='o5GoF3EinFZ6LZgz0YiI', max_length=20),
        ),
    ]
