# Generated by Django 3.2 on 2024-04-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0144_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='dpz3OQwtumvEj0emvpiQ', max_length=20),
        ),
    ]
