# Generated by Django 3.2 on 2024-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0145_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='yPi3ZErJ0ey5YiNNpdNB', max_length=20),
        ),
    ]
