# Generated by Django 3.2 on 2024-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0146_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='NyjtNJS8EhQFD8XzWvuS', max_length=20),
        ),
    ]
