# Generated by Django 3.2 on 2024-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0148_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='p06on6o8rmyAjRWrcGbw', max_length=20),
        ),
    ]
