# Generated by Django 3.2 on 2024-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0149_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='oeyxIxjk6DEvID9VN8kf', max_length=20),
        ),
    ]
