# Generated by Django 3.2 on 2024-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0151_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='WrI4m2L0HHO3wm57Dfey', max_length=20),
        ),
    ]
