# Generated by Django 3.2 on 2024-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0152_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Ii34CLnCv6hKglx0Rj4t', max_length=20),
        ),
    ]
