# Generated by Django 3.2 on 2024-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0154_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='wbTmBd6wdeR6s71rGakb', max_length=20),
        ),
    ]
