# Generated by Django 3.2 on 2024-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0155_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='If5bCidsVB74ZcUwIPdS', max_length=20),
        ),
    ]
