# Generated by Django 3.2 on 2024-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0156_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='NDvuUoaRCbWUHRmgbADN', max_length=20),
        ),
    ]
