# Generated by Django 3.2 on 2024-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0158_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='G4AKAmyncm5eVa2kSisd', max_length=20),
        ),
    ]
