# Generated by Django 3.2 on 2024-04-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0160_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='7BI1LHcjxSlV6Jdnog0w', max_length=20),
        ),
    ]
