# Generated by Django 3.2 on 2024-04-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0161_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='BQUjmAEub58NxQxCTme1', max_length=20),
        ),
    ]
