# Generated by Django 3.2 on 2024-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0162_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='OsxnsUeuM9i64j4HHZJU', max_length=20),
        ),
    ]
