# Generated by Django 3.2 on 2024-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0163_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='WwQpfnx6mtC3mbCVkuGr', max_length=20),
        ),
    ]
