# Generated by Django 3.2 on 2024-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0164_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='hvqAs9XkNLH4KWp90a0e', max_length=20),
        ),
    ]
