# Generated by Django 3.2 on 2024-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0165_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='c97U8fw1MbF1YGnvxj6Z', max_length=20),
        ),
    ]
