# Generated by Django 3.2 on 2024-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0166_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='H8lcAr9DQQRqNR71C5vT', max_length=20),
        ),
    ]
