# Generated by Django 3.2 on 2024-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0170_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Y7UT8iNO1h3MmNbA2ZrJ', max_length=20),
        ),
    ]
