# Generated by Django 3.2 on 2024-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0171_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='wNhTaDEebODtlpXZNvfz', max_length=20),
        ),
    ]
