# Generated by Django 3.2 on 2024-05-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0175_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='WiBORqLB7zuuBGB0E558', max_length=20),
        ),
    ]
