# Generated by Django 3.2 on 2024-05-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0176_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='ZDjOzGkY9KDNqndwmsB0', max_length=20),
        ),
    ]
