# Generated by Django 3.2 on 2024-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0177_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='uxFBznH6n8lzWx0ETrAq', max_length=20),
        ),
    ]
