# Generated by Django 3.2 on 2024-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0179_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='XXVjjeanpDHzOVfLIsDB', max_length=20),
        ),
    ]
