# Generated by Django 3.2 on 2024-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0181_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='qKN6VVV00NbX22oLiOTf', max_length=20),
        ),
    ]
