# Generated by Django 3.2 on 2024-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0182_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='3yQB69JRaWTTC9WXb8ZO', max_length=20),
        ),
    ]
