# Generated by Django 3.2 on 2024-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0184_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='uTtoxtZ8yTIn1dzeEcbt', max_length=20),
        ),
    ]
