# Generated by Django 3.2 on 2024-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0187_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='mwrE5l7gczYX545tJraU', max_length=20),
        ),
    ]
