# Generated by Django 3.2 on 2024-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0188_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='7Rj0fBD7ALtCgq4bXtw0', max_length=20),
        ),
    ]
