# Generated by Django 3.2 on 2024-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0190_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='4W68U7q7LvuM4HPd25q5', max_length=20),
        ),
    ]
