# Generated by Django 3.2 on 2024-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0191_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='2kG956hLmSkn9LH7iOdS', max_length=20),
        ),
    ]
