# Generated by Django 3.2 on 2024-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0192_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Djb1IasfiV9ryCyoxaMl', max_length=20),
        ),
    ]
