# Generated by Django 3.2 on 2024-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0194_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='VKNzaR8clQsLyknv2qeM', max_length=20),
        ),
    ]
