# Generated by Django 3.2 on 2024-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0195_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='2bzoqE8ErI4MgMt9Y7dd', max_length=20),
        ),
    ]
