# Generated by Django 3.2 on 2024-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0196_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='2BmhQSnTLcCWrm9Y5Llh', max_length=20),
        ),
    ]
