# Generated by Django 3.2 on 2024-05-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0199_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='YGU3hDPy3QixSYGgeSdv', max_length=20),
        ),
    ]
