# Generated by Django 3.2 on 2024-05-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0200_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='1tKEmd02GnGUMAhcjRCh', max_length=20),
        ),
    ]
