# Generated by Django 3.2 on 2024-05-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0202_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='T0dK9uzuhcEABbsBPvI3', max_length=20),
        ),
    ]
