# Generated by Django 3.2 on 2024-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0208_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='6i0xEuTBvgAIYGAnTiE8', max_length=20),
        ),
    ]
