# Generated by Django 3.2 on 2024-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0212_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='OnUdBzsCxXftUXyLkKFw', max_length=20),
        ),
    ]
