# Generated by Django 3.2 on 2024-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0215_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='oXpjevJpZhjRmXwZISYN', max_length=20),
        ),
    ]
