# Generated by Django 3.2 on 2024-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0216_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='b6luOKpeQ7ZFOMez5HXJ', max_length=20),
        ),
    ]
