# Generated by Django 3.2 on 2024-06-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0217_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='vlJytPBnymtGZvPbJHdr', max_length=20),
        ),
    ]
