# Generated by Django 3.2 on 2024-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0219_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='W76OX0tgnAuvUS2q3iqQ', max_length=20),
        ),
    ]
