# Generated by Django 3.2 on 2024-06-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0220_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='3x1duZhFvI0YjhfZARzG', max_length=20),
        ),
    ]
