# Generated by Django 3.2 on 2024-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0221_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='EHIURm4GQvRqqvOC7xfw', max_length=20),
        ),
    ]
