# Generated by Django 3.2 on 2024-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0222_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='GuqVslS15EkNG53az24t', max_length=20),
        ),
    ]
