# Generated by Django 3.2 on 2024-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0223_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='bbZsk4UbTqsQdiIO2OSt', max_length=20),
        ),
    ]
