# Generated by Django 3.2 on 2024-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0224_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='3tFvdZShSEzTGr1BQFVD', max_length=20),
        ),
    ]
