# Generated by Django 3.2 on 2024-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0227_auto_20240611_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='hWhmtefNIArJIGzbcDh4', max_length=20),
        ),
    ]
