# Generated by Django 3.2 on 2024-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0228_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Iurz5IdDu4nZCTWlxP1u', max_length=20),
        ),
    ]
