# Generated by Django 3.2 on 2024-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0229_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='pPJmQb5XPQYGn2UIyuIw', max_length=20),
        ),
    ]
