# Generated by Django 3.2 on 2024-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0230_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='ILEhSoG3WBWhpFdbGmAK', max_length=20),
        ),
    ]
