# Generated by Django 3.2 on 2024-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0231_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='kQiZ5GrrNxKStjCuemj5', max_length=20),
        ),
    ]
