# Generated by Django 3.2 on 2024-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0235_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Bh7DMXhXLSgglGdkifHk', max_length=20),
        ),
    ]
