# Generated by Django 3.2 on 2024-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0236_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='ny3NP5MKHpxhDXSkumKq', max_length=20),
        ),
    ]
