# Generated by Django 3.2 on 2024-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0237_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='rbhfCrZA5i3AeYo7seXx', max_length=20),
        ),
    ]
