# Generated by Django 3.2 on 2024-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0238_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='InGZq906TuzIPDBiyAII', max_length=20),
        ),
    ]
