# Generated by Django 3.2 on 2024-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0239_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='supr0EB3on7MPOo49xGp', max_length=20),
        ),
    ]
