# Generated by Django 3.2 on 2024-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0240_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='kxObD5FBO4oGCoIu2mri', max_length=20),
        ),
    ]
