# Generated by Django 3.2 on 2024-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0241_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='9L76PaVaCqtjYGcCfMqB', max_length=20),
        ),
    ]
