# Generated by Django 3.2 on 2024-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0242_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='l3IEECsif3zXuBp6UxPF', max_length=20),
        ),
    ]
