# Generated by Django 3.2 on 2024-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0243_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='coXhXAydNTJm480DKLBx', max_length=20),
        ),
    ]
