# Generated by Django 3.2 on 2024-07-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0244_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='J7wqY2YyDHvSDJcK4sSM', max_length=20),
        ),
    ]
