# Generated by Django 3.2 on 2024-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0245_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='49pXseAOVsjxETEuU3xP', max_length=20),
        ),
    ]
