# Generated by Django 3.2 on 2024-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0246_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='8cWskzWPfS219iRhPWEA', max_length=20),
        ),
    ]
