# Generated by Django 3.2 on 2024-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0247_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='YpvU3bJ5XAHUpSpGXdya', max_length=20),
        ),
    ]
