# Generated by Django 3.2 on 2024-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0248_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='xNEDGVZF4Yk1EB2fqqqg', max_length=20),
        ),
    ]
