# Generated by Django 3.2 on 2024-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0249_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='VJnia5ikAEgAeqyTcLNV', max_length=20),
        ),
    ]
