# Generated by Django 3.2 on 2024-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0250_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Z6kxKr4RcewnAWBnuevy', max_length=20),
        ),
    ]
