# Generated by Django 3.2 on 2024-07-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0251_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='LOFXs6Z4wHhw6sw7pe7W', max_length=20),
        ),
    ]
