# Generated by Django 3.2 on 2024-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0252_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='fXKiJ27L1G9DrA3nQPwp', max_length=20),
        ),
    ]
