# Generated by Django 3.2 on 2024-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0253_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='njiksWCMebPr3UsofB44', max_length=20),
        ),
    ]
