# Generated by Django 3.2 on 2024-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0254_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='jZRGgKd2ks1JHdZgbxeo', max_length=20),
        ),
    ]
