# Generated by Django 3.2 on 2024-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0255_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Fsv7AllvtKgt2HHzBVs2', max_length=20),
        ),
    ]
