# Generated by Django 3.2 on 2024-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0256_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='RMzBcepwMlTcF2SH9ip5', max_length=20),
        ),
    ]
