# Generated by Django 3.2 on 2024-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0257_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Asd0nJ2qRu111XMgRxge', max_length=20),
        ),
    ]
