# Generated by Django 3.2 on 2024-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0258_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='YrhCG1VNtyjetZS1r7Sx', max_length=20),
        ),
    ]
