# Generated by Django 3.2 on 2024-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0259_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='HO0FDLSVV0st4tciUGSo', max_length=20),
        ),
    ]
