# Generated by Django 3.2 on 2024-07-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0260_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='0Vu1SUCJj4SVyZLasO1h', max_length=20),
        ),
    ]
