# Generated by Django 3.2 on 2024-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0261_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='9jjC1nUVRhZi8XLKAGva', max_length=20),
        ),
    ]
