# Generated by Django 3.2 on 2024-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0262_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='nEU1arDmy4DDLaFo8HJX', max_length=20),
        ),
    ]
