# Generated by Django 3.2 on 2024-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0263_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Y97h4tICLEtFUzDd6o3H', max_length=20),
        ),
    ]
