# Generated by Django 3.2 on 2024-08-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0264_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='ssLa35MoshqH5ygzkGvk', max_length=20),
        ),
    ]
