# Generated by Django 3.2 on 2024-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0265_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='kEnspjGGW1xdbNj6nqyv', max_length=20),
        ),
    ]
