# Generated by Django 3.2 on 2024-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0267_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='vQbhncrtloUhSIzexg4l', max_length=20),
        ),
    ]
