# Generated by Django 3.2 on 2024-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0269_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='6dPeYJ6LonfSvWO5OYOv', max_length=20),
        ),
    ]
