# Generated by Django 3.2.8 on 2023-10-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_operation_type_document_i'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_Form',
            new_name='Payment_Forms',
        ),
    ]
