# Generated by Django 3.2.8 on 2023-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.JSONField()),
                ('employee', models.JSONField()),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History_Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.JSONField(blank=True, null=True)),
                ('amount', models.JSONField(blank=True, null=True)),
                ('customer', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
