# Generated by Django 3.2.8 on 2023-10-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_history_pass_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
