# Generated by Django 3.2.8 on 2023-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='annulled',
            field=models.BooleanField(default=False),
        ),
    ]
