# Generated by Django 3.2.8 on 2023-10-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_annulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_invoice',
            name='action',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Modified', 'Modified'), ('Deleted', 'Deleted'), ('Annulled', 'Annulled')], max_length=10, null=True),
        ),
    ]
