# Generated by Django 3.2.8 on 2023-12-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_details_invoice_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
