# Generated by Django 3.2.8 on 2023-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_pass',
            name='employee',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='employee',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
