# Generated by Django 3.2.8 on 2024-02-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0101_alter_employee_psswd'),
        ('invoice', '0014_invoice_cufe'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
    ]
