# Generated by Django 3.2.8 on 2024-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_note_credit_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_credit_product',
            name='quantity_send',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
