# Generated by Django 3.2.8 on 2024-03-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0111_alter_branch_psswd'),
        ('invoice', '0017_note_credit_product_quantity_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
        migrations.AddField(
            model_name='history_pass',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
