# Generated by Django 3.2 on 2024-04-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0128_alter_employee_psswd'),
        ('company', '0132_alter_branch_psswd'),
        ('customer', '0011_alter_associate_person_email'),
        ('invoice', '0018_auto_20240304_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.IntegerField()),
                ('number', models.IntegerField()),
                ('prefix', models.CharField(max_length=7)),
                ('date', models.CharField(max_length=12)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('annulled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
    ]
