# Generated by Django 3.2 on 2024-04-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_alter_tax_name'),
        ('invoice', '0019_remission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Forms_Remission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.CharField(max_length=12)),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
                ('remission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.remission')),
            ],
        ),
        migrations.CreateModel(
            name='PassRemission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pass', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('employee', models.JSONField(blank=True, null=True)),
                ('remission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.remission')),
            ],
        ),
        migrations.CreateModel(
            name='Details_Remission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('ipo', models.FloatField()),
                ('discount', models.FloatField()),
                ('tax_value', models.IntegerField(blank=True, default=0, null=True)),
                ('remission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.remission')),
            ],
        ),
    ]
