# Generated by Django 3.2 on 2024-04-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0135_alter_branch_psswd'),
        ('setting', '0015_alter_tax_name'),
        ('customer', '0011_alter_associate_person_email'),
        ('user', '0131_alter_employee_psswd'),
        ('invoice', '0021_details_service_passservice_payment_forms_service_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.IntegerField()),
                ('number', models.IntegerField()),
                ('prefix', models.CharField(max_length=7)),
                ('date', models.CharField(max_length=12)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('annulled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Forms_Cotization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.CharField(max_length=12)),
                ('cotization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.cotization')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='PassCotization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pass', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('employee', models.JSONField(blank=True, null=True)),
                ('cotization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.cotization')),
            ],
        ),
        migrations.CreateModel(
            name='Details_Cotization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('ipo', models.FloatField()),
                ('discount', models.FloatField()),
                ('tax_value', models.IntegerField(blank=True, default=0, null=True)),
                ('cotization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.cotization')),
            ],
        ),
    ]
