# Generated by Django 3.2 on 2024-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_cotization_details_cotization_passcotization_payment_forms_cotization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cufe',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
