# Generated by Django 3.2 on 2024-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_auto_20240502_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='UUID',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
