# Generated by Django 3.2 on 2024-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_invoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cadena_original',
            field=models.CharField(blank=True, max_length=3024, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_cert',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='no_cert_dig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='no_cert_sat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sello_cfdi',
            field=models.CharField(blank=True, max_length=2024, null=True),
        ),
    ]
