# Generated by Django 3.2 on 2024-05-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_auto_20240507_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
