# Generated by Django 3.2 on 2024-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
