# Generated by Django 3.2 on 2024-05-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20240501_1850'),
        ('invoice', '0027_invoice_state_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
