# Generated by Django 3.2 on 2024-05-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0044_auto_20240508_1809'),
        ('invoice', '0029_auto_20240522_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='seller_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.sellerinfo'),
        ),
    ]
