# Generated by Django 3.2 on 2024-05-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0194_alter_branch_psswd'),
        ('customer', '0013_auto_20240501_1554'),
        ('user', '0190_alter_employee_psswd'),
        ('setting', '0045_alter_historygeneral_class_models'),
        ('inventory', '0022_product_price_init'),
        ('invoice', '0030_invoice_seller_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.IntegerField()),
                ('number', models.IntegerField()),
                ('prefix', models.CharField(max_length=7)),
                ('date', models.CharField(max_length=12)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('annulled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Forms_OrderBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.CharField(max_length=12)),
                ('order_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.orderbuy')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='Details_OrderBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('ipo', models.FloatField()),
                ('discount', models.FloatField()),
                ('tax_value', models.IntegerField(blank=True, default=0, null=True)),
                ('order_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.orderbuy')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
