# Generated by Django 3.2 on 2024-05-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_price_init'),
        ('invoice', '0031_details_orderbuy_orderbuy_payment_forms_orderbuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbuy',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderbuy',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
            preserve_default=False,
        ),
    ]
