# Generated by Django 3.2 on 2024-05-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_item_type'),
        ('user', '0193_alter_employee_psswd'),
        ('company', '0197_alter_branch_psswd'),
        ('invoice', '0032_auto_20240524_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.IntegerField()),
                ('number', models.IntegerField()),
                ('prefix', models.CharField(max_length=7)),
                ('date', models.CharField(max_length=12)),
                ('date_venc', models.CharField(max_length=12)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('annulled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
