# Generated by Django 3.2 on 2024-05-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0045_alter_historygeneral_class_models'),
        ('inventory', '0023_product_item_type'),
        ('invoice', '0033_invoiceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Forms_InvoiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.CharField(max_length=12)),
                ('order_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceprovider')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='Details_InvoiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('ipo', models.FloatField()),
                ('discount', models.FloatField()),
                ('tax_value', models.IntegerField(blank=True, default=0, null=True)),
                ('order_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceprovider')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
