# Generated by Django 3.2 on 2024-05-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_details_invoiceprovider_payment_forms_invoiceprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details_invoiceprovider',
            old_name='order_buy',
            new_name='invoice_provider',
        ),
        migrations.RenameField(
            model_name='payment_forms_invoiceprovider',
            old_name='order_buy',
            new_name='invoice_provider',
        ),
    ]
