# Generated by Django 3.2 on 2024-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_auto_20240530_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprovider',
            name='order_buy',
            field=models.ManyToManyField(blank=True, null=True, to='invoice.OrderBuy'),
        ),
    ]
