# Generated by Django 3.2 on 2024-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_invoiceprovider_order_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_invoice',
            field=models.CharField(blank=True, choices=[('Pagada', 'Pagada'), ('Borrador', 'Borrador'), ('Cancelada', 'Cancelada'), ('Por cobrar', 'Por cobrar')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(blank=True, choices=[('Timbrada', 'Timbrada'), ('No timbrada', 'No timbrada'), ('Cancelada', 'Cancelada')], max_length=256, null=True),
        ),
    ]
