# Generated by Django 3.2 on 2024-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0037_auto_20240530_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(blank=True, choices=[('Timbrada', 'Timbrada'), ('No timbrada', 'No timbrada'), ('Cancelada', 'Cancelada')], default='No timbrada', max_length=256, null=True),
        ),
    ]
