# Generated by Django 3.2 on 2024-05-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_alter_invoice_state_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state_email',
            field=models.CharField(blank=True, choices=[('Email enviado', 'Email enviado'), ('Email no enviado', 'Email no enviado')], default='Email no enviado', max_length=256, null=True),
        ),
    ]
