# Generated by Django 3.2 on 2024-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0040_alter_invoice_state_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(blank=True, choices=[('Timbrada', 'Timbrada'), ('No timbrada', 'No timbrada'), ('Cancelado', 'Cancelado')], default='No timbrada', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state_invoice',
            field=models.CharField(blank=True, choices=[('Pagada', 'Pagada'), ('Borrador', 'Borrador'), ('Cancelado', 'Cancelado'), ('Por cobrar', 'Por cobrar')], max_length=256, null=True),
        ),
    ]
