# Generated by Django 3.2 on 2024-05-31 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0041_auto_20240531_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(blank=True, choices=[('Timbrada', 'Timbrada'), ('No timbrada', 'No timbrada'), ('Cancelado', 'Cancelado'), ('Vigente', 'Vigente')], default='No timbrada', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state_invoice',
            field=models.CharField(blank=True, choices=[('Pagada', 'Pagada'), ('Borrador', 'Borrador'), ('Cancelado', 'Cancelado'), ('Vigente', 'Vigente'), ('Por cobrar', 'Por cobrar')], max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='BillToPayInvoiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.TextField()),
                ('employee', models.JSONField(blank=True, null=True)),
                ('invoice_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceprovider')),
            ],
        ),
    ]
