# Generated by Django 3.2 on 2024-05-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0042_auto_20240531_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprovider',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
