# Generated by Django 3.2 on 2024-05-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0043_alter_invoiceprovider_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtopayinvoiceprovider',
            name='employee',
        ),
    ]
