# Generated by Django 3.2 on 2024-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0044_remove_billtopayinvoiceprovider_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtopayinvoiceprovider',
            name='employee',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
