# Generated by Django 3.2 on 2024-05-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_item_type'),
        ('setting', '0047_alter_historygeneral_class_models'),
        ('invoice', '0045_billtopayinvoiceprovider_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.TextField()),
                ('employee', models.JSONField(blank=True, null=True)),
                ('invoice_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceprovider')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
