# Generated by Django 3.2 on 2024-05-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0047_alter_historygeneral_class_models'),
        ('customer', '0013_auto_20240501_1554'),
        ('invoice', '0046_paymentinvoiceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.TextField()),
                ('employee', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentToPayInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.TextField()),
                ('employee', models.JSONField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
    ]
