# Generated by Django 3.2 on 2024-06-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0048_alter_historygeneral_class_models'),
        ('invoice', '0047_auto_20240531_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uso_cfdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.cfdi'),
        ),
    ]
