# Generated by Django 3.2 on 2024-06-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0049_auto_20240625_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoiceprovider',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
