# Generated by Django 3.2 on 2024-07-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0052_alter_historygeneral_class_models'),
        ('company', '0240_alter_branch_psswd'),
        ('invoice', '0050_alter_paymentinvoiceprovider_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.bank'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='payment_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form'),
        ),
    ]
