# Generated by Django 3.2 on 2024-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0051_auto_20240701_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type_document',
            field=models.IntegerField(choices=[(1, 'Invoice'), (2, 'Invoice Transfer'), (3, 'Ticket'), (4, 'Nota Credito')], default=1),
        ),
    ]
