# Generated by Django 3.2 on 2024-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0052_alter_invoice_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='assigned',
            field=models.IntegerField(default=0),
        ),
    ]
