# Generated by Django 3.2 on 2024-07-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0240_alter_employee_psswd'),
        ('company', '0244_alter_branch_psswd'),
        ('customer', '0013_auto_20240501_1554'),
        ('setting', '0052_alter_historygeneral_class_models'),
        ('invoice', '0053_service_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFrequent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('frequent', models.IntegerField()),
                ('observation', models.TextField()),
                ('number_account', models.CharField(max_length=156)),
                ('total', models.FloatField(blank=True, null=True)),
                ('type_invoice', models.TextField(choices=[('Factura de venta', 'Factura de venta'), ('Factura de arrendamiento', 'Factura de arrendamiento')], default='Factura de venta')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
                ('list_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_price', to='setting.list_price')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
                ('seller_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.sellerinfo')),
                ('serie_folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.seriefolio')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='company.store')),
                ('term_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.termpayment')),
                ('uso_cfdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.cfdi')),
            ],
        ),
    ]
