# Generated by Django 3.2 on 2024-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0054_invoicefrequent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefrequent',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
