# Generated by Django 3.2 on 2024-07-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_product_image_b64'),
        ('invoice', '0055_invoicefrequent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsInvoiceFrequent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('ipo', models.FloatField()),
                ('discount', models.FloatField()),
                ('tax_value', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicefrequent')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
