# Generated by Django 3.2 on 2024-07-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0052_alter_historygeneral_class_models'),
        ('invoice', '0056_detailsinvoicefrequent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reason_cancel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.motivocancel'),
        ),
    ]
