# Generated by Django 3.2 on 2024-07-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0057_invoice_reason_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoiceprovider',
            name='conciliation',
            field=models.BooleanField(default=False),
        ),
    ]
