# Generated by Django 3.2 on 2024-07-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0052_alter_historygeneral_class_models'),
        ('invoice', '0058_paymentinvoiceprovider_conciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttopayinvoice',
            name='term_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.termpayment'),
        ),
    ]
