# Generated by Django 3.2 on 2024-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0059_paymenttopayinvoice_term_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pie_invoice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term_and_cond',
            field=models.TextField(blank=True, null=True),
        ),
    ]
