# Generated by Django 3.2 on 2024-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0060_auto_20240706_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
