# Generated by Django 3.2 on 2024-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0061_invoice_status_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='conciliation',
            field=models.BooleanField(default=False),
        ),
    ]
