# Generated by Django 3.2 on 2024-07-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0063_auto_20240718_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotization',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='cotization',
            name='state_email',
            field=models.CharField(blank=True, choices=[('Email enviado', 'Email enviado'), ('Email no enviado', 'Email no enviado')], default='Email no enviado', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cotization',
            name='status_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='state_email',
            field=models.CharField(blank=True, choices=[('Email enviado', 'Email enviado'), ('Email no enviado', 'Email no enviado')], default='Email no enviado', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
