# Generated by Django 3.2 on 2024-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0065_auto_20240722_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
