# Generated by Django 3.2 on 2024-07-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0067_invoicefromticket_ticketgeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type_document',
            field=models.IntegerField(choices=[(1, 'Invoice'), (2, 'Invoice Transfer'), (3, 'Ticket'), (4, 'Nota Credito'), (5, 'Ticket invoice')], default=1),
        ),
        migrations.AlterField(
            model_name='ticketgeneral',
            name='invoice_from_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoicefromticket'),
        ),
    ]
