# Generated by Django 3.2 on 2024-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0068_auto_20240726_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefromticket',
            name='month',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicefromticket',
            name='period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
