# Generated by Django 3.2 on 2024-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0069_auto_20240726_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='UUID',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='cadena_original',
            field=models.CharField(blank=True, max_length=3024, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='cufe',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='date_cert',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='no_cert_dig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='no_cert_sat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='sello_cfdi',
            field=models.CharField(blank=True, max_length=2024, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='state',
            field=models.CharField(blank=True, choices=[('Timbrada', 'Timbrada'), ('No timbrada', 'No timbrada'), ('Cancelado', 'Cancelado'), ('Vigente', 'Vigente')], default='No timbrada', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='state_email',
            field=models.CharField(blank=True, choices=[('Email enviado', 'Email enviado'), ('Email no enviado', 'Email no enviado')], default='Email no enviado', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='status_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
