# Generated by Django 3.2 on 2024-08-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0070_auto_20240813_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='imp_saldo_ant',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='imp_saldo_insoluto',
            field=models.FloatField(default=0),
        ),
    ]
