# Generated by Django 3.2 on 2024-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0071_auto_20240823_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='parcialidad',
            field=models.IntegerField(default=1),
        ),
    ]
