# Generated by Django 3.2 on 2024-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0072_paymentinvoice_parcialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
