# Generated by Django 3.2 on 2024-09-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0054_termandcond_state_account'),
        ('invoice', '0073_paymentinvoice_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_forms',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method'),
        ),
    ]
