# Generated by Django 3.2 on 2024-09-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0074_alter_payment_forms_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcToInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('nc_to_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.nctoinvoice')),
            ],
        ),
    ]
