# Generated by Django 3.2.8 on 2023-10-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0004_payment_form_payment_method'),
        ('inventory', '0003_auto_20231010_1626'),
        ('company', '0011_alter_branch_psswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_registration', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFormShopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.CharField(max_length=10)),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_form')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.payment_method')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shopping')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('cost', models.FloatField()),
                ('price_1', models.FloatField()),
                ('price_2', models.FloatField()),
                ('price_3', models.FloatField()),
                ('ipo', models.FloatField()),
                ('discount', models.FloatField()),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shopping')),
            ],
        ),
    ]
