# Generated by Django 3.2.8 on 2023-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.JSONField()),
                ('employee', models.JSONField()),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
