# Generated by Django 3.2.8 on 2023-12-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20231228_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
