# Generated by Django 3.2.8 on 2023-12-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_shopping_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_shopping',
            name='invoice',
        ),
        migrations.AddField(
            model_name='history_shopping',
            name='shopping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history_shopping',
            name='supplier',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_shopping',
            name='employee',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
