# Generated by Django 3.2.8 on 2023-12-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20231228_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping', models.JSONField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('customer', models.JSONField(blank=True, null=True)),
                ('employee', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
