# Generated by Django 3.2.8 on 2024-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_history_pass_number_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_pass',
            name='number_transaction',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
